name: Build and Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pyinstaller
      - run: pyinstaller --windowed --onefile --name beer-analizer-win.exe main.py
      - uses: actions/upload-artifact@v4
        with:
          name: beer-analizer-win
          path: dist/beer-analizer-win.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install python3-tk -y
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pyinstaller
      - run: pyinstaller --windowed --onefile --name beer-analizer-linux main.py
      - uses: actions/upload-artifact@v4
        with:
          name: beer-analizer-linux
          path: dist/beer-analizer-linux

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: |
          docker run --platform linux/arm64 --rm -v $(pwd):/src -w /src arm64v8/python:3.12 bash -c "
            pip install pyinstaller &&
            pyinstaller --windowed --onefile --name beer-analizer-linux-arm64 main.py
          "
      - uses: actions/upload-artifact@v4
        with:
          name: beer-analizer-linux-arm64
          path: dist/beer-analizer-linux-arm64

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pyinstaller
      - run: pyinstaller --windowed --onefile --name beer-analizer-macos-arm64 main.py
      - uses: actions/upload-artifact@v4
        with:
          name: beer-analizer-macos-arm64
          path: dist/beer-analizer-macos-arm64

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-linux-arm64, build-macos-arm64]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: beer-analizer-win
          path: dist/
      - uses: actions/download-artifact@v4
        with:
          name: beer-analizer-linux
          path: dist/
      - uses: actions/download-artifact@v4
        with:
          name: beer-analizer-linux-arm64
          path: dist/
      - uses: actions/download-artifact@v4
        with:
          name: beer-analizer-macos-arm64
          path: dist/
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/beer-analizer-win.exe
            dist/beer-analizer-linux
            dist/beer-analizer-linux-arm64
            dist/beer-analizer-macos-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}